name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  PORT : 22
  HOST: 44.212.72.194
  USER: ubuntu
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls;ls
    - name: ls
      run: ls
    - name: SCP Files 
      uses: appleboy/scp-action@master
      with:
          host: ${{env.HOST}}
          username: ${{env.USER}}
          port: ${{env.PORT}}
          key: ${{secrets.PASSWORD}}
          source: "*"
          target: "backend"

    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
       HOST: ${{env.HOST}}
       USER: ${{env.USER}}
       PRIVATE_SSH_KEY: ${{ secrets.PASSWORD }}
       COMMAND:  cd backend; 
                 pm2 stop run;
                 pm2 del run;
                 pm2 start run.sh
    

