name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  PORT : 22
  HOST: pacheco.chillan.ubiobio.cl
  USER: franciscolizana1801
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls;ls
    - name: ls
      run: ls
    - name: SCP Files 
      uses: appleboy/scp-action@master
      with:
          host: ${{env.HOST}}
          username: ${{env.USER}}
          port: ${{env.PORT}}
          key: ${{secrets.PASSWORD}}
          source: "*"
          target: "backend"

    

